### ISSUE TITLE
Planned functionallity Roadmap

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/intellij-plugin-openrewriter#5]
Planned:
- [ ] Support for text-based recipes
  - [ ] Building/Displaying rewrite.yml files (e.g. something like markdown preview)
  - [ ] Auto-completion for recipes / rewrite.yml files
  - [ ] Support for running them
- [ ] Support for the [OpenRewrite Marketplace by Moderene](https://app.moderne.io/marketplace)
